### ISSUE TITLE
getAuthorizeURL 请求地址错误

### ISSUE THREAD

**Issue by thenbsp** [henter/WeChat-OAuth#1]
问题一：

\Henter\WeChat\OAuth.php 第 95 行

``` php
return "https://open.weixin.qq.com/connect/qrconnect?" . http_build_query($params);
```

改成

``` php
return "https://open.weixin.qq.com/connect/oauth2/authorize?" . http_build_query($params);
```

问题二：

\Henter\WeChat\OAuth.php 第 88 行

``` php
$scope = 'snsapi_login'
```

改成

``` php
$scope = 'snsapi_base'
```

$scope 参数只有 snsapi_base 和 snsapi_userinfo 两种，官方文档中关于网页授权的两种scope的区别说明：

http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html#.E7.AC.AC.E5.9B.9B.E6.AD.A5.EF.BC.9A.E6.8B.89.E5.8F.96.E7.94.A8.E6.88.B7.E4.BF.A1.E6.81.AF.28.E9.9C.80scope.E4.B8.BA_snsapi_userinfo.29

**Comment by henter** [comment]
你好，
这个地址是用于公众号授权用的
https://open.weixin.qq.com/connect/oauth2/authorize?  

这个是普通用户二维码登陆
https://open.weixin.qq.com/connect/qrconnect?

详见官方文档：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&lang=zh_CN (https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&lang=zh_CN&token=e9cff70cd335a7f70b266318015c454504982429)

谢谢回复！  

## 

Henter
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by phoenixg** [comment]
same issue, 好像这个类库对网页授权不支持吧？
