### ISSUE TITLE
composer update的问题

### ISSUE THREAD

**Issue by panxianhai** [henter/WeChat-OAuth#2]
[InvalidArgumentException]  
  Could not find package henter/wechat-oauth at any version for your minimum-stability (stable). Check the package spelling or your minimum-stabi  
  lity

**Comment by henter** [comment]
@panxianhai 你设置的版本是啥？

可以用 `"henter/wechat-oauth": "1.0"`  或 `"henter/wechat-oauth": "dev-master"`

**Comment by panxianhai** [comment]
两个都试过，都是一样的ix返回信息

2015-10-29 15:36 GMT+08:00 Henter notifications@github.com:

**Comment by henter** [comment]
方便把composer.json发出来看看吗？

Sent from Outlook

On Thu, Oct 29, 2015 at 2:07 AM -0700, "Hevin" notifications@github.com wrote:

两个都试过，都是一样的ix返回信息

2015-10-29 15:36 GMT+08:00 Henter notifications@github.com:

**Comment by panxianhai** [comment]
{
   "require": {
      "php": ">=5.3.8",
      "pingplusplus/pingpp-php": "dev-master",
      "qiniu/php-sdk": "dev-master",
       "henter/wechat-oauth": "dev-master"
   }
}

2015-10-29 17:42 GMT+08:00 Henter notifications@github.com:

**Comment by panxianhai** [comment]
_➜ \* *mech *_git:(**master**) *_✗_ composer update

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1

```
- The requested package henter/wechat-oauth could not be found in any
```

version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to
  your minimum-stability setting
  
  see <
  https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for
  more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further
common problems.

2015-10-30 9:33 GMT+08:00 盘先海 panxianhai@gmail.com:

**Comment by henter** [comment]
> {
>    "require": {
>       "php": ">=5.3.8",
>       "pingplusplus/pingpp-php": "dev-master",
>       "qiniu/php-sdk": "dev-master",
>        "henter/wechat-oauth": "dev-master"
>    }
> }

 我用这个配置能正常update
